<?xml version="1.0" encoding="utf-8"?><Database Name="DbAssetJGC" Class="DCAssetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=DbAssetJGC;Integrated Security=True" SettingsObjectName="CORE.JGC.Properties.Settings" SettingsPropertyName="DbAssetJGCConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.Get_Login" Method="Get_Login">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Get_LoginResult">
      <Column Name="Jumlah" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UtilUser_View" Method="UtilUser_View">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="UtilUser_ViewResult">
      <Column Name="UserName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeptCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DeptName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="bManager" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bLogin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GroupAccessCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LogOutDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MobStockOpnameListAsset_View" Method="MobStockOpnameListAsset_View">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(15)" />
    <ElementType Name="MobStockOpnameListAsset_ViewResult">
      <Column Name="AssetCode" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetBrandCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AssetModelCode" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DeptCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CompanyCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Floor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignTo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MobTrackingAsset" Method="MobTrackingAsset">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(15)" />
    <ElementType Name="MobTrackingAssetResult">
      <Column Name="Urut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssetCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Site" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Floor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssignTo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StatusFrom" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Event" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetBrand_IUD" Method="MsAssetBrand_IUD">
    <Parameter Name="BrandCode" Parameter="brandCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="BrandName" Parameter="brandName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsAssetBrand_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetBrand_View" Method="MsAssetBrand_View">
    <Parameter Name="BrandCode" Parameter="brandCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsAssetBrand_ViewResult">
      <Column Name="BrandCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BrandName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetCategory_IUD" Method="MsAssetCategory_IUD">
    <Parameter Name="CategoryCode" Parameter="categoryCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CategoryName" Parameter="categoryName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsAssetCategory_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetCategory_View" Method="MsAssetCategory_View">
    <Parameter Name="CategoryCode" Parameter="categoryCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsAssetCategory_ViewResult">
      <Column Name="AssetCategoryCode" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="AssetCategoryName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetModel_IUD" Method="MsAssetModel_IUD">
    <Parameter Name="ModelCode" Parameter="modelCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ModelName" Parameter="modelName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="BrandCode" Parameter="brandCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsAssetModel_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetModel_View" Method="MsAssetModel_View">
    <Parameter Name="ModelCode" Parameter="modelCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsAssetModel_ViewResult">
      <Column Name="ModelCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ModelName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="BrandCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetStatus_IUD" Method="MsAssetStatus_IUD">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="NamaStatus" Parameter="namaStatus" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsAssetStatus_IUDResult">
      <Column Name="Exx" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetStatus_View" Method="MsAssetStatus_View">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsAssetStatus_ViewResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetType_IUD" Method="MsAssetType_IUD">
    <Parameter Name="TypeCode" Parameter="typeCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="TypeName" Parameter="typeName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsAssetType_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAssetType_View" Method="MsAssetType_View">
    <Parameter Name="TypeCode" Parameter="typeCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsAssetType_ViewResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssetTypeCode" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="AssetTypeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsCompany_IUD" Method="MsCompany_IUD">
    <Parameter Name="CompanyCode" Parameter="companyCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CompanyName" Parameter="companyName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Province" Parameter="province" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PostalCode" Parameter="postalCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="bActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="PhotoLogo" Parameter="photoLogo" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsCompany_IUDResult">
      <Column Name="" Member="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsCompany_View" Method="MsCompany_View">
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsCompany_ViewResult">
      <Column Name="CompanyID" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="bActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="uby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Uon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsCurrency_IUD" Method="MsCurrency_IUD">
    <Parameter Name="CurrencyCode" Parameter="currencyCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CurrencyName" Parameter="currencyName" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsCurrency_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsCurrency_View" Method="MsCurrency_View">
    <Parameter Name="CurrencyCode" Parameter="currencyCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsCurrency_ViewResult">
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsDepartment_IUD" Method="MsDepartment_IUD">
    <Parameter Name="DeptCode" Parameter="deptCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="DeptName" Parameter="deptName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsDepartment_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsDepartment_View" Method="MsDepartment_View">
    <Parameter Name="DeptCode" Parameter="deptCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsDepartment_ViewResult">
      <Column Name="DeptCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsEmployee_IUD" Method="MsEmployee_IUD">
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.String" DbType="VarChar(7)" />
    <Parameter Name="LocationCode" Parameter="locationCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="DeptCode" Parameter="deptCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="bActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsEmployee_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsEmployee_View" Method="MsEmployee_View">
    <Parameter Name="EmployeeId" Parameter="employeeId" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsEmployee_ViewResult">
      <Column Name="EmployeeId" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DeptCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DeptName" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsExchangeRate_IUD" Method="MsExchangeRate_IUD">
    <Parameter Name="CurrencyCode" Parameter="currencyCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CurrencyCodeConvert" Parameter="currencyCodeConvert" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ExchangeRate" Parameter="exchangeRate" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsExchangeRate_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsExchangeRate_View" Method="MsExchangeRate_View">
    <Parameter Name="CurrencyCode" Parameter="currencyCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CurrencyCodeConvert" Parameter="currencyCodeConvert" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsExchangeRate_ViewResult">
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CurrencyCodeConvert" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsLocation_IUD" Method="MsLocation_IUD">
    <Parameter Name="LocationCode" Parameter="locationCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LocationName" Parameter="locationName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Floor" Parameter="floor" Type="System.Int32" DbType="Int" />
    <Parameter Name="bActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsLocation_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsLocation_View" Method="MsLocation_View">
    <Parameter Name="LocationCode" Parameter="locationCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsLocation_ViewResult">
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsSite_IUD" Method="MsSite_IUD">
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="SiteName" Parameter="siteName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="PostalCode" Parameter="postalCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="bActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsSite_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsSite_View" Method="MsSite_View">
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsSite_ViewResult">
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="bActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsStatus_IUD" Method="MsStatus_IUD">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NamaStatus" Parameter="namaStatus" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsStatus_IUDResult">
      <Column Name="Exx" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsStatus_View" Method="MsStatus_View">
    <Parameter Name="Status" Parameter="status" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsStatus_ViewResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsSupplier_IUD" Method="MsSupplier_IUD">
    <Parameter Name="SupplierCode" Parameter="supplierCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="SupplierName" Parameter="supplierName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="PIC" Parameter="pIC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="City" Parameter="city" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Province" Parameter="province" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PostalCode" Parameter="postalCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Telephone" Parameter="telephone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="bActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsSupplier_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsSupplier_View" Method="MsSupplier_View">
    <Parameter Name="SupplierCode" Parameter="supplierCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsSupplier_ViewResult">
      <Column Name="SupplierCode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PIC" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="bActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsType_IUD" Method="MsType_IUD">
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="NamaType" Parameter="namaType" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsType_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsType_View" Method="MsType_View">
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsType_ViewResult">
      <Column Name="Type" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NamaType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Pop_AssetCheckIn" Method="Pop_AssetCheckIn">
    <ElementType Name="Pop_AssetCheckInResult">
      <Column Name="AssetTagID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Pop_AssetCheckOut" Method="Pop_AssetCheckOut">
    <ElementType Name="Pop_AssetCheckOutResult">
      <Column Name="AssetTagID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Pop_AssetDisposeAsset" Method="Pop_AssetDisposeAsset">
    <ElementType Name="Pop_AssetDisposeAssetResult">
      <Column Name="AssetTagID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Pop_AssetMaintenance" Method="Pop_AssetMaintenance">
    <ElementType Name="Pop_AssetMaintenanceResult">
      <Column Name="AssetTagID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Pop_AssetTransfer" Method="Pop_AssetTransfer">
    <ElementType Name="Pop_AssetTransferResult">
      <Column Name="AssetTagID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Rpt_AssetPastDue" Method="Rpt_AssetPastDue">
    <ElementType Name="Rpt_AssetPastDueResult">
      <Column Name="AssetTagID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssetBrand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AssignTo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Rpt_WarrantyExpiring" Method="Rpt_WarrantyExpiring">
    <ElementType Name="Rpt_WarrantyExpiringResult">
      <Column Name="AssetTagId" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="WarrantyExpired" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Active" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxCheckIn_IUD" Method="TrxCheckIn_IUD">
    <Parameter Name="CheckInNo" Parameter="checkInNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ReturnDate" Parameter="returnDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LocationCode" Parameter="locationCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Floor" Parameter="floor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxCheckIn_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxCheckIn_View" Method="TrxCheckIn_View">
    <Parameter Name="CheckInNo" Parameter="checkInNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="TrxCheckIn_ViewResult">
      <Column Name="CheckInNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NamaType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReturnDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxCheckInLine_IUD" Method="TrxCheckInLine_IUD">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxCheckInLine_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxCheckInLine_View" Method="TrxCheckInLine_View">
    <Parameter Name="CheckInNo" Parameter="checkInNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="TrxCheckInLine_ViewResult">
      <Column Name="CheckInNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AssetCode" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxCheckOut_IUD" Method="TrxCheckOut_IUD">
    <Parameter Name="CheckOutNo" Parameter="checkOutNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CheckOutDate" Parameter="checkOutDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CheckOutDueDate" Parameter="checkOutDueDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AssignTo" Parameter="assignTo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LocationCode" Parameter="locationCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Floor" Parameter="floor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxCheckOut_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxCheckOut_View" Method="TrxCheckOut_View">
    <Parameter Name="CheckOutNo" Parameter="checkOutNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="TrxCheckOut_ViewResult">
      <Column Name="CheckOutNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NamaType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CheckOutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CheckOutDueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AssignTo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxCheckOutLine_IUD" Method="TrxCheckOutLine_IUD">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxCheckOutLine_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxCheckOutLine_View" Method="TrxCheckOutLine_View">
    <Parameter Name="CheckOutNo" Parameter="checkOutNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="TrxCheckOutLine_ViewResult">
      <Column Name="CheckOutNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AssetCode" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxDisposeAsset_IUD" Method="TrxDisposeAsset_IUD">
    <Parameter Name="DisposeNo" Parameter="disposeNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="DisposeDate" Parameter="disposeDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DisposeTo" Parameter="disposeTo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Reason" Parameter="reason" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxDisposeAsset_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxDisposeAsset_View" Method="TrxDisposeAsset_View">
    <Parameter Name="DisposeNo" Parameter="disposeNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="TrxDisposeAsset_ViewResult">
      <Column Name="DisposeNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DisposeDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxDisposeAssetLine_IUD" Method="TrxDisposeAssetLine_IUD">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxDisposeAssetLine_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxDisposeAssetLine_View" Method="TrxDisposeAssetLine_View">
    <Parameter Name="DisposeNo" Parameter="disposeNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="TrxDisposeAssetLine_ViewResult">
      <Column Name="DisposeNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AssetCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxMaintenanceAsset_IUD" Method="TrxMaintenanceAsset_IUD">
    <Parameter Name="MaintenanceAssetNo" Parameter="maintenanceAssetNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ScheduleDate" Parameter="scheduleDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CompleteDate" Parameter="completeDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="AssignTo" Parameter="assignTo" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Damage" Parameter="damage" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Cost" Parameter="cost" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxMaintenanceAsset_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxMaintenanceAsset_View" Method="TrxMaintenanceAsset_View">
    <Parameter Name="MaintenanceAssetNo" Parameter="maintenanceAssetNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="TrxMaintenanceAsset_ViewResult">
      <Column Name="MaintenanceAssetNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="NamaType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompleteDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AssignTo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Damage" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="iPrint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxMaintenanceAssetLine_IUD" Method="TrxMaintenanceAssetLine_IUD">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxMaintenanceAssetLine_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxMaintenanceAssetLine_View" Method="TrxMaintenanceAssetLine_View">
    <Parameter Name="MaintenanceAssetNo" Parameter="maintenanceAssetNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="TrxMaintenanceAssetLine_ViewResult">
      <Column Name="MaintenanceAssetNo" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AssetCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="AssetSerialNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SiteCode" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="SiteName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="LocationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxTransferAsset_IUD" Method="TrxTransferAsset_IUD">
    <Parameter Name="TransferAssetNo" Parameter="transferAssetNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Type" Parameter="type" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TransferDate" Parameter="transferDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TransferAssetNoRef" Parameter="transferAssetNoRef" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LocationCode" Parameter="locationCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Floor" Parameter="floor" Type="System.Int32" DbType="Int" />
    <Parameter Name="Notes" Parameter="notes" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxTransferAsset_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TrxTransferAssetLine_IUD" Method="TrxTransferAssetLine_IUD">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="TrxTransferAssetLine_IUDResult">
      <Column Name="" Member="Column1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UtilGroupMenu_IUD" Method="UtilGroupMenu_IUD">
    <Parameter Name="GroupMenuCode" Parameter="groupMenuCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="GroupMenuName" Parameter="groupMenuName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="UtilGroupMenu_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UtilGroupMenu_View" Method="UtilGroupMenu_View">
    <Parameter Name="GroupMenuCode" Parameter="groupMenuCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="UtilGroupMenu_ViewResult">
      <Column Name="GroupMenuCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupMenuName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UtilMenu_IUD" Method="UtilMenu_IUD">
    <Parameter Name="MenuCode" Parameter="menuCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="MenuName" Parameter="menuName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MenuPath" Parameter="menuPath" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="LevelMenu" Parameter="levelMenu" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParentMenu" Parameter="parentMenu" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="UtilMenu_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.UtilMenu_View" Method="UtilMenu_View">
    <Parameter Name="MenuCode" Parameter="menuCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="UtilMenu_ViewResult">
      <Column Name="MenuCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MenuPath" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="LevelMenu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentMenu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Iby" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.UtilUser_IUD" Method="UtilUser_IUD">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="DeptCode" Parameter="deptCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="LocationCode" Parameter="locationCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="GroupAccessCode" Parameter="groupAccessCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="bActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="bManager" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="UtilUser_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsQrCode_IUD" Method="MsQrCode_IUD">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="Qrcode" Parameter="qrcode" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsQrCode_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAsset_IUD" Method="MsAsset_IUD">
    <Parameter Name="AssetName" Parameter="assetName" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="AssetBrandCode" Parameter="assetBrandCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="AssetModelCode" Parameter="assetModelCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="AssetCategoryCode" Parameter="assetCategoryCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="AssetSerialNo" Parameter="assetSerialNo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="AssetTypeCode" Parameter="assetTypeCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="bActive" Type="System.Int32" DbType="Int" />
    <Parameter Name="bCapitalized" Type="System.Int32" DbType="Int" />
    <Parameter Name="Photo" Parameter="photo" Type="System.String" DbType="VarChar(MAX)" />
    <Parameter Name="SiteCode" Parameter="siteCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LocationCode" Parameter="locationCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Floor" Parameter="floor" Type="System.Int32" DbType="Int" />
    <Parameter Name="PurchaseNo" Parameter="purchaseNo" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CurrencyCode" Parameter="currencyCode" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="PurchasePrice" Parameter="purchasePrice" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="PurchaseDate" Parameter="purchaseDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="SupplierCode" Parameter="supplierCode" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="CompanyID" Parameter="companyID" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="DeptCode" Parameter="deptCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="WarrantyMonth" Parameter="warrantyMonth" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserID" Parameter="userID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="No" Parameter="no" Type="System.Int32" DbType="Int" />
    <ElementType Name="MsAsset_IUDResult">
      <Column Name="Status" Type="System.String" DbType="VarChar(23) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.MsAsset_View" Method="MsAsset_View">
    <Parameter Name="AssetCode" Parameter="assetCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Tipe" Parameter="tipe" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="MsAsset_ViewResult">
      <Column Name="AssetPhoto" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="AssetTagID" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetBrand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PurchaseDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PurchasePrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NamaStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CurrencyCode" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>